name: Publier un livre sur Mastodon

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: mastodon-bot
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout le dépôt
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Nettoyer le cache npm
        run: npm cache clean --force
      - name: Afficher les variables d'environnement
        run: |
          echo "MASTODON_ACCES_TOKEN est défini ? : ${{secrets.MASTODON_BASE_URL != '' }}"
          echo "MASTODON_BASE_URL est défini ? : ${{secrets.MASTODON_BASE_URL != '' }}"
      - name: installer les dépendances
          env:
            NODE_OPTIONS: "--openssl-legacy-provider"
          run: npm ci
      - name: Publier le livre (avec détails)
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BAS_URL }}
        run: |
          node --trace-warnings index.js || echo "Le script à échoué avec le code : $?"
